export const sampleData = [
    {
        id: 1,
        title: 'Ticket 1',
        price: 100,
        destinationCity: 'New York',
        departureCity: 'London',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 2,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 2,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'New York',
        departureCity: 'London',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 2,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 3,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'mashhad',
        departureCity: 'London',
        departureDate: '2022-10-10',
        returnDate: '2022-10-20',
        numberOfPassengers: 2,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 4,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'New York',
        departureCity: 'London',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 10,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 5,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'tehran',
        departureCity: 'ghazvin',
        departureDate: '2021-10-10',
        returnDate: '2020-12-10',
        numberOfPassengers: 2,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 6,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
        image: 'https://picsum.photos/200/300',
    },
    {
        id: 7,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
    {
        id: 8,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
    {
        id: 9,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
    {
        id: 10,
        title: 'Ticket 2',
        price: 200,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
    {
        id: 11,
        title: 'Ticket test cheap',
        price: 50,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
    {
        id: 12,
        title: 'Ticket 2',
        price: 100,
        destinationCity: 'esfahan',
        departureCity: 'tehran',
        departureDate: '2021-10-10',
        returnDate: '2021-10-20',
        numberOfPassengers: 5,
    },
];
